apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/argocd"
type: Opaque
stringData:
  username: <username>
  #TOKEN: s.0t5yCxZKvm0fgUmNL6YR74c51
